# Generated by Django 4.2.2 on 2023-06-18 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v1', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v2', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v3', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v4', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v5', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v6', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v7', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v8', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v9', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v10', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v11', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v12', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v13', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v14', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v15', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v16', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v17', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v18', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v19', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v20', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v21', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v22', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v23', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v24', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v25', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v26', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v27', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('v28', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-9999.99), django.core.validators.MaxValueValidator(9999.99)])),
                ('predictions', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
